# Configuration

# Application Settings
app:
  name: "testproject"
  version: "1.0.0"
  description: "A powerful web application built with flux Framework"
  environment: "development" 
  debug: true
  timezone: "UTC"
  secret_key: "change-this-to-your-own-secure-secret-key"
  log_level: "info" 

# Server Configuration
server:
  host: "localhost"
  port: 3000
  base_path: "/"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s

# Database Configuration
database:
  # Main database connection
  default:
    driver: "sqlite" 
    name: "flux.db"
    # Uncomment these below for other database types
    # host: "localhost"
    # port: 3306  
    # username: "flux_user"
    # password: "flux_password"
    # ssl_mode: "disable" 
    # charset: "utf8mb4"
    # timezone: "Local"
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_life: 3600s 
    slow_threshold: 200ms
    log_level: "info" 
    debug: false


auth:
  jwt:
    secret_key: "change-this-to-your-own-personal-jwt-secret-key"
    expiration: 86400 
    refresh_expiration: 604800 
    signing_method: "HS256" 


view:
  engine: "go-template" 
  directory: "templates"
  extension: ".gohtml"
  cache: true
